// Code generated by protoc-gen-go. DO NOT EDIT.
// source: report/report.proto

package report

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product int32

const (
	Product_UNKOWN      Product = 0
	Product_ANDROID_SDK Product = 1
	Product_IOS_SDK     Product = 2
)

var Product_name = map[int32]string{
	0: "UNKOWN",
	1: "ANDROID_SDK",
	2: "IOS_SDK",
}

var Product_value = map[string]int32{
	"UNKOWN":      0,
	"ANDROID_SDK": 1,
	"IOS_SDK":     2,
}

func (x Product) String() string {
	return proto.EnumName(Product_name, int32(x))
}

func (Product) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_653c1f6daa56f8fb, []int{0}
}

// 上报消息类型，留出后期扩展的空间
type Type int32

const (
	Type_UNKNOWN        Type = 0
	Type_GAME_START     Type = 10
	Type_LOGIN_INIT     Type = 20
	Type_LOGIN_SUCC     Type = 21
	Type_LOGIN_SUBMIT   Type = 22
	Type_PAY_INIT       Type = 30
	Type_PAY_SUCC       Type = 31
	Type_PAY_SUBMIT     Type = 32
	Type_HEARTBEAT      Type = 40
	Type_HEARTBEAT_STOP Type = 41
	Type_BI_DATA        Type = 50
)

var Type_name = map[int32]string{
	0:  "UNKNOWN",
	10: "GAME_START",
	20: "LOGIN_INIT",
	21: "LOGIN_SUCC",
	22: "LOGIN_SUBMIT",
	30: "PAY_INIT",
	31: "PAY_SUCC",
	32: "PAY_SUBMIT",
	40: "HEARTBEAT",
	41: "HEARTBEAT_STOP",
	50: "BI_DATA",
}

var Type_value = map[string]int32{
	"UNKNOWN":        0,
	"GAME_START":     10,
	"LOGIN_INIT":     20,
	"LOGIN_SUCC":     21,
	"LOGIN_SUBMIT":   22,
	"PAY_INIT":       30,
	"PAY_SUCC":       31,
	"PAY_SUBMIT":     32,
	"HEARTBEAT":      40,
	"HEARTBEAT_STOP": 41,
	"BI_DATA":        50,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_653c1f6daa56f8fb, []int{1}
}

// 数据上报消息结构
type ReportRequestBody struct {
	Product              Product           `protobuf:"varint,1,opt,name=product,proto3,enum=report.Product" json:"product,omitempty"`
	Type                 Type              `protobuf:"varint,2,opt,name=type,proto3,enum=report.Type" json:"type,omitempty"`
	Version              uint32            `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp            int64             `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload              map[string]string `protobuf:"bytes,5,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReportRequestBody) Reset()         { *m = ReportRequestBody{} }
func (m *ReportRequestBody) String() string { return proto.CompactTextString(m) }
func (*ReportRequestBody) ProtoMessage()    {}
func (*ReportRequestBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_653c1f6daa56f8fb, []int{0}
}

func (m *ReportRequestBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequestBody.Unmarshal(m, b)
}
func (m *ReportRequestBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequestBody.Marshal(b, m, deterministic)
}
func (m *ReportRequestBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequestBody.Merge(m, src)
}
func (m *ReportRequestBody) XXX_Size() int {
	return xxx_messageInfo_ReportRequestBody.Size(m)
}
func (m *ReportRequestBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequestBody.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequestBody proto.InternalMessageInfo

func (m *ReportRequestBody) GetProduct() Product {
	if m != nil {
		return m.Product
	}
	return Product_UNKOWN
}

func (m *ReportRequestBody) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_UNKNOWN
}

func (m *ReportRequestBody) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ReportRequestBody) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ReportRequestBody) GetPayload() map[string]string {
	if m != nil {
		return m.Payload
	}
	return nil
}

// 数据上报响应结构
type ReportResponseBody struct {
	Ok                   int32             `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Errmsg               string            `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReportResponseBody) Reset()         { *m = ReportResponseBody{} }
func (m *ReportResponseBody) String() string { return proto.CompactTextString(m) }
func (*ReportResponseBody) ProtoMessage()    {}
func (*ReportResponseBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_653c1f6daa56f8fb, []int{1}
}

func (m *ReportResponseBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportResponseBody.Unmarshal(m, b)
}
func (m *ReportResponseBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportResponseBody.Marshal(b, m, deterministic)
}
func (m *ReportResponseBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportResponseBody.Merge(m, src)
}
func (m *ReportResponseBody) XXX_Size() int {
	return xxx_messageInfo_ReportResponseBody.Size(m)
}
func (m *ReportResponseBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportResponseBody.DiscardUnknown(m)
}

var xxx_messageInfo_ReportResponseBody proto.InternalMessageInfo

func (m *ReportResponseBody) GetOk() int32 {
	if m != nil {
		return m.Ok
	}
	return 0
}

func (m *ReportResponseBody) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *ReportResponseBody) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("report.Product", Product_name, Product_value)
	proto.RegisterEnum("report.Type", Type_name, Type_value)
	proto.RegisterType((*ReportRequestBody)(nil), "report.ReportRequestBody")
	proto.RegisterMapType((map[string]string)(nil), "report.ReportRequestBody.PayloadEntry")
	proto.RegisterType((*ReportResponseBody)(nil), "report.ReportResponseBody")
	proto.RegisterMapType((map[string]string)(nil), "report.ReportResponseBody.DataEntry")
}

func init() { proto.RegisterFile("report/report.proto", fileDescriptor_653c1f6daa56f8fb) }

var fileDescriptor_653c1f6daa56f8fb = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x6b, 0xe7, 0x1f, 0x99, 0xa6, 0xe9, 0x32, 0xb4, 0x95, 0x55, 0x21, 0xb0, 0x2a, 0x84,
	0xd2, 0x1e, 0x8c, 0x94, 0x1e, 0xa8, 0x7a, 0xc2, 0xae, 0x43, 0xb1, 0x42, 0x1d, 0x77, 0xed, 0x08,
	0xc1, 0xc5, 0x32, 0x64, 0x45, 0xa3, 0x34, 0x59, 0xd7, 0xde, 0x54, 0xf2, 0x8b, 0xf0, 0x00, 0x1c,
	0xb9, 0x20, 0xde, 0x10, 0x79, 0xd7, 0x6e, 0x10, 0x9c, 0x38, 0x65, 0x7f, 0x33, 0xdf, 0x37, 0xf9,
	0xbc, 0x63, 0xc3, 0x93, 0x8c, 0xa5, 0x3c, 0x13, 0xaf, 0xd4, 0x8f, 0x95, 0x66, 0x5c, 0x70, 0x6c,
	0x2b, 0x3a, 0xfa, 0xa6, 0xc3, 0x63, 0x2a, 0x8f, 0x94, 0xdd, 0xad, 0x59, 0x2e, 0x1c, 0x3e, 0x2b,
	0xf0, 0x18, 0x3a, 0x69, 0xc6, 0x67, 0xeb, 0x2f, 0xc2, 0xd0, 0x4c, 0x6d, 0xd0, 0x1f, 0xee, 0x5a,
	0x95, 0x3b, 0x50, 0x65, 0x5a, 0xf7, 0xd1, 0x84, 0xa6, 0x28, 0x52, 0x66, 0xe8, 0x52, 0xd7, 0xab,
	0x75, 0x51, 0x91, 0x32, 0x2a, 0x3b, 0x68, 0x40, 0xe7, 0x9e, 0x65, 0xf9, 0x9c, 0xaf, 0x8c, 0x86,
	0xa9, 0x0d, 0x76, 0x68, 0x8d, 0xf8, 0x14, 0xba, 0x62, 0xbe, 0x64, 0xb9, 0x48, 0x96, 0xa9, 0xd1,
	0x34, 0xb5, 0x41, 0x83, 0x6e, 0x0a, 0xf8, 0x06, 0x3a, 0x69, 0x52, 0xdc, 0xf2, 0x64, 0x66, 0xb4,
	0xcc, 0xc6, 0x60, 0x7b, 0xf8, 0xb2, 0x1e, 0xfe, 0x4f, 0x60, 0x2b, 0x50, 0xc2, 0xd1, 0x4a, 0x64,
	0x05, 0xad, 0x6d, 0x87, 0xe7, 0xd0, 0xfb, 0xb3, 0x81, 0x04, 0x1a, 0x0b, 0x56, 0xc8, 0x47, 0xea,
	0xd2, 0xf2, 0x88, 0x7b, 0xd0, 0xba, 0x4f, 0x6e, 0xd7, 0x2a, 0x7e, 0x97, 0x2a, 0x38, 0xd7, 0xcf,
	0xb4, 0xa3, 0x9f, 0x1a, 0x60, 0xfd, 0x3f, 0x79, 0xca, 0x57, 0x39, 0x93, 0x37, 0xd3, 0x07, 0x9d,
	0x2f, 0xe4, 0x84, 0x16, 0xd5, 0xf9, 0x02, 0x0f, 0xa0, 0xcd, 0xb2, 0x6c, 0x99, 0x7f, 0xad, 0x26,
	0x54, 0x84, 0x67, 0xd0, 0x9c, 0x25, 0x22, 0x31, 0x1a, 0x32, 0xf9, 0x8b, 0xbf, 0x93, 0x6f, 0x26,
	0x5a, 0x6e, 0x22, 0x12, 0x95, 0x5b, 0x3a, 0x0e, 0x5f, 0x43, 0xf7, 0xa1, 0xf4, 0x3f, 0x89, 0x4f,
	0x4e, 0xa1, 0x53, 0x6d, 0x07, 0x01, 0xda, 0x53, 0x7f, 0x3c, 0xf9, 0xe0, 0x93, 0x2d, 0xdc, 0x85,
	0x6d, 0xdb, 0x77, 0xe9, 0xc4, 0x73, 0xe3, 0xd0, 0x1d, 0x13, 0x0d, 0xb7, 0xa1, 0xe3, 0x4d, 0x42,
	0x09, 0xfa, 0xc9, 0x2f, 0x0d, 0x9a, 0xe5, 0xae, 0xca, 0xea, 0xd4, 0x1f, 0xfb, 0xca, 0xd3, 0x07,
	0xb8, 0xb4, 0xaf, 0x46, 0x71, 0x18, 0xd9, 0x34, 0x22, 0x50, 0xf2, 0xfb, 0xc9, 0xa5, 0xe7, 0xc7,
	0x9e, 0xef, 0x45, 0x64, 0x6f, 0xc3, 0xe1, 0xf4, 0xe2, 0x82, 0xec, 0x23, 0x81, 0x5e, 0xcd, 0xce,
	0x95, 0x17, 0x91, 0x03, 0xec, 0xc1, 0xa3, 0xc0, 0xfe, 0xa8, 0xf4, 0xcf, 0x6a, 0x92, 0xea, 0xe7,
	0xa5, 0x5b, 0x91, 0xd4, 0x9a, 0xb8, 0x03, 0xdd, 0x77, 0x23, 0x9b, 0x46, 0xce, 0xc8, 0x8e, 0xc8,
	0x00, 0x11, 0xfa, 0x0f, 0x18, 0x87, 0xd1, 0x24, 0x20, 0xc7, 0x65, 0x3a, 0xc7, 0x8b, 0x5d, 0x3b,
	0xb2, 0xc9, 0xd0, 0x79, 0x0b, 0xb8, 0x62, 0xc2, 0xba, 0x9b, 0xdf, 0x70, 0x6e, 0xe5, 0xb3, 0x45,
	0x9c, 0xae, 0xf3, 0x1b, 0xa7, 0xad, 0xee, 0x36, 0xd8, 0xfa, 0x54, 0xbd, 0xdb, 0xdf, 0xf5, 0xd6,
	0x75, 0xe8, 0x8e, 0x83, 0x1f, 0xfa, 0xfe, 0xb5, 0x94, 0x86, 0x95, 0xb4, 0xda, 0xc2, 0xe7, 0xb6,
	0xfc, 0x14, 0x4e, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x53, 0xab, 0x75, 0x59, 0x21, 0x03, 0x00,
	0x00,
}
